### ISSUE TITLE
add sunrise time and sunset time

### ISSUE THREAD

**Issue by cagnulein** [ErwinSteffens/darksky-influxdb#4]
I think sunrise and sunset times should be useful (think about a solar system).
I think the best way to put this info in influxdb should be adding a boolean variable with the value of the sun in that very moment.

For example if we have sunrise at 7:32 and sunset at 18:47 we would have:
0:00 sun=0
1:00 sun=0
..
7:32 sun=1
8:00 sun=1
10:00 sun=1
..
18:47 sun=0
20:00 sun=0
23:00 sun=0
..

what do you think?

**Comment by ErwinSteffens** [comment]
Yes, I think this is the correct approach, but only sunset does not say everything for solar systems. 

Maybe also these fields:

```
"cloudCover": 0.62,
"uvIndex": 1,
"visibility": 9.32,
"ozone": 268.95
```

**Comment by cagnulein** [comment]
Do you think to add them soon?

**Comment by ErwinSteffens** [comment]
You can create an pull request if you want to add them..

**Comment by cagnulein** [comment]
let's continue there https://github.com/ErwinSteffens/darksky-influxdb/pull/5
